### ISSUE TITLE
DB Integrity Check

### ISSUE THREAD

**Issue by jonasgwt** [sjb-deck/deck#199]
Run every (?)

* Item quantity 
    ~~* from creation, iterate through all the orders, adding and removing quantity and check with current quantity~~
    * Check if quantity of each item expiry matches with total quantity
* LoanOrder
    * If the loan is active, should not have return date. If it is not active, should have return date
* Order
    * If order reason is Others, it should have a `other_info` 

@cheehengk for kits

**Comment by cheehengk** [comment]
Blueprint Check
- fields check, all exists and valid
- check no archived blueprints is in use by any unretired kit
- check content requirements, all item_id exists, retired or not

Kit Check
- fields check, all exists and valid
- check blueprint was checked and not archived
- check that status matches last history commit
- check that content matches last history snapshot
- check content is valid, even if incomplete, all item_expiry_id exists and is part of _item that exists in corresponding blueprint
- check that content is not overloaded


Check to (?) long ago
History Check
- fields check, all exists and valid
- check that most recent snapshot is corrected reflected as current kit content
- check order_id exists and valid
- check if changes in the order matches the difference between the two affected snapshots
- if loan, check return date is after due date
- if loan, check that if kit status is on_loan, then there isn't a return date
- check that kit is not overdue
