### ISSUE TITLE
Create helper method to check kit expiry

### ISSUE THREAD

**Issue by jonasgwt** [sjb-deck/deck#219]
* Return kits and their expiry if it is expiring in 1 month
* Tests

Note: To return the expiring kit with its earliest expiring item.

Would be useful to write a helper method to get nearest expiry of an item in a kit

**Comment by cheehengk** [comment]
Return kits with at least one item expiring within one month (30 days). Within each kit returned, item(s) expiring within one month will be returned together and sorted by nearest expiry dates.
