### ISSUE TITLE
Change to pointer on hover

### ISSUE THREAD

**Issue by jonasgwt** [sjb-deck/deck#38]
Icon on the top left of navbar is clickable, as a user I would expect it to convert to a pointer

Current:

https://github.com/sjb-deck/deck/assets/55698556/3e28a6e4-4f56-42d2-aa5f-9b4522e37ac6

Expected:
Would expect a similar pointer on the navbar
<img width="137" alt="image" src="https://github.com/sjb-deck/deck/assets/55698556/92755f82-eae8-40e9-91e5-7c79dd1fb7e8">

**Comment by karenhernandeze** [comment]
Can I be assigned?
