### ISSUE TITLE
Issue with over-withdrawal

### ISSUE THREAD

**Issue by cheehengk** [sjb-deck/deck#68]
![Screenshot 2023-07-19 at 10 08 21 AM](https://github.com/sjb-deck/deck/assets/88090694/939af6f9-7073-49f4-8179-5d8593e7e8a1)

Over withdrawal can result in negative values.

Suggestion:
* Do a frontend check with javascript function.
* Add layer of protection in api endpoint.

**Comment by jonasgwt** [comment]
frontend check added in https://github.com/sjb-deck/deck/pull/95

**Comment by jonasgwt** [comment]
Duplicate of #72 and #97
